name: Run Polaris Extract and Upload SARIF

on:
  workflow_dispatch:

jobs:
  extract-findings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run extract_findings.py
        env:
          POLARIS_URL: ${{ secrets.POLARIS_URL }}
          POLARIS_TOKEN: ${{ secrets.POLARIS_TOKEN }}
        run: |
          cd "Polaris python code"
          python extract_findings.py "$POLARIS_URL" "$POLARIS_TOKEN" 35

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "Polaris python code/polaris_issues.sarif"
